name: echemdb-website
channels:
  - conda-forge
  - defaults
dependencies:
  - astropy
  - black
  - echemdb>=0.6.0,<0.7.0
  - isort
  - make
  # In early 2022 we had trouble with some recent versions of mkdocs. To work around this issue, we pin mkdocs versions exactly. This pin can likely be relaxed again.
  - mkdocs=1.3.0
  - myst-nb>=0.17.0,<0.18.0
  - myst-parser>=0.18.0,<0.19.0
  - pip
  - pylatexenc>=2.10,<3
  - pylint
  - pytest
  - pytest-doctestplus
  - pytest-xdist
  - pytest-remotedata
  - svgdigitizer>=0.10,<0.11
  - pip:
    - linkchecker
    # In early 2022 we had trouble with some recent versions of mkdocs. To work around this issue, we pin mkdocs plugin versions exactly. This pin can likely be relaxed again.
    - mkdocs-gen-files==0.3.4
    # In early 2022 we had trouble with some recent versions of mkdocs. To work around this issue, we pin mkdocs plugin versions exactly. This pin can likely be relaxed again.
    - mkdocs-literate-nav==0.4.1
    # In early 2022 we had trouble with some recent versions of mkdocs. To work around this issue, we pin mkdocs plugin versions exactly. This pin can likely be relaxed again.
    - mkdocs-macros-plugin==0.6.4
    # In early 2022 we had trouble with some recent versions of mkdocs. To work around this issue, we pin mkdocs plugin versions exactly. This pin can likely be relaxed again.
    - mkdocs-material==8.2.5
    # In early 2022 we had trouble with some recent versions of mkdocs. To work around this issue, we pin mkdocs plugin versions exactly. This pin can likely be relaxed again.
    - mkdocs-material-extensions==1.0.3
    # In early 2022 we had trouble with some recent versions of mkdocs. To work around this issue, we pin mkdocs plugin versions exactly. This pin can likely be relaxed again.
    - mkdocs-section-index==0.3.3
    - markdown-include
    - mdutils
    - pymdown-extensions>=9.2,<10
    - python-frontmatter
    - tabulate
