name: echemdb
channels:
  - conda-forge
  - defaults
dependencies:
  - astropy
  - black
  - filelock
  - frictionless
  - inflect
  - jupyterlab
  - jupytext
  - make
  - matplotlib
  # In early 2022 we had trouble with some recent versions of mkdocs. To work around this issue, we pin mkdocs versions exactly. This pin can likely be relaxed again.
  - mkdocs=1.3.0
  - myst-nb>=0.13.0,<0.14.0
  - myst-parser>=0.15,<0.17
  - pandas
  - pip
  - plotly
  - pybtex
  - pytest
  - pytest-doctestplus
  - pytest-xdist
  - pytest-remotedata
  - pyyaml
  - sphinx>=4.3,<5
  - pip:
    - linkchecker
    # In early 2022 we had trouble with some recent versions of mkdocs. To work around this issue, we pin mkdocs plugin versions exactly. This pin can likely be relaxed again.
    - mkdocs-gen-files==0.3.4
    # In early 2022 we had trouble with some recent versions of mkdocs. To work around this issue, we pin mkdocs plugin versions exactly. This pin can likely be relaxed again.
    - mkdocs-literate-nav==0.4.1
    # In early 2022 we had trouble with some recent versions of mkdocs. To work around this issue, we pin mkdocs plugin versions exactly. This pin can likely be relaxed again.
    - mkdocs-macros-plugin==0.6.4
    # In early 2022 we had trouble with some recent versions of mkdocs. To work around this issue, we pin mkdocs plugin versions exactly. This pin can likely be relaxed again.
    - mkdocs-material==8.2.5
    # In early 2022 we had trouble with some recent versions of mkdocs. To work around this issue, we pin mkdocs plugin versions exactly. This pin can likely be relaxed again.
    - mkdocs-material-extensions==1.0.3
    # In early 2022 we had trouble with some recent versions of mkdocs. To work around this issue, we pin mkdocs plugin versions exactly. This pin can likely be relaxed again.
    - mkdocs-section-index==0.3.3
    - markdown-include
    - mdutils
    - pymdown-extensions>=9.2,<10
    - python-frontmatter
    - sphinx_rtd_theme>=1,<2
    - svgdigitizer>=0.5.0,<0.6.0
    - tabulate
